# This is a basic workflow to help you get started with Actions

name: All-Tests
# Controls when the workflow will run
on:
  # Triggers the workflow e.g. on push or pull request events but only for the "master" branch
 
  # Allows you to run this workflow manually from the Actions tab
    push:
      branches:
        - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script(Test)
        run: 'mvn clean test -DdriverType="CHROME-REMOTE" -Denvironment="http://advantage.proficom.de:8080/#/" -DsuiteXmlFile="testsuites/advantageshop/All-Tests.xml"'

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()   # run this step even if previous step failed
        with:
          name: Junit Tests            # Name of the check run which will be created
          path: '**/target/surefire-reports/junitreports/TEST-*.xml'   # Path to test results
          reporter: java-junit        # Format of test results


      - name: Test-Summary
        uses: test-summary/action@v2
        with:
          paths: '**/target/surefire-reports/junitreports/TEST-*.xml'
        if: always()
      
      - name: Save Test-Report
        uses: actions/upload-artifact@v4
        with:
          name: Test-Automation-Report
          path: '**/target/surefire-reports/**'
     
