# This is a basic workflow to help you get started with Actions

name: TC-04-ContactUs

# Controls when the workflow will run
on:
  # Triggers the workflow e.g. on push or pull request events but only for the "master" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkout:
    runs-on: self-windows
    steps:
      - uses: actions/checkout@v3
    
  # This workflow contains a job called "build"
  Test:
    needs: checkout 
    # The type of runner that the job will run on
    runs-on: self-windows

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      # Runs a single command using the runners shell
      - name: Run a one-line script(Test)
        run: 'mvn clean test -DdriverType="CHROME-REMOTE" -Denvironment="http://advantage.proficom.de:8080/#/" -DsuiteXmlFile="testsuites/advantageshop/TC-04-ContactUs.xml"'
      
      - name: Save Test-Report
        uses: actions/upload-artifact@v4
        with:
          name: Test-Automation-Report
          path: '**/target/surefire-reports/**'
     
